sudo: required

services:
  - docker

script:
    # Set up your docker hub account in travis setting
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - git config --global user.email "byang1217@gmail.com"
  - git config --global user.name "Bin Yang"
  - git config --global color.ui auto
  - chmod 644 ~/.gitconfig
  - mkdir -p ~/.ssh
    # Set up your ssh private key in travis setting
    # SSH_KEY_BASE64: cat ~/.ssh/id_rsa | base64 -w 0
  - echo "$SSH_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
    # SSH_KEY_BASE64: cat ~/.ssh/config | base64 -w 0
  - echo "$SSH_CONFIG_BASE64" | base64 -d > ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - if [ "$TRAVIS_BRANCH" = "master" ]; then DOCKER_IMG_TAG="latest"; else DOCKER_IMG_TAG="$TRAVIS_BRANCH"; fi
    # Download the code base of StarlingX
  - time ./build.sh /stx-ci/scripts/stx-repo-init || exit 1
    # Create the mirror of upstream packages from cengn. It is much faster than downloading from original upstream URLs
  - time ./build.sh /stx-ci/scripts/stx-mirror-init || exit 1
    # Create the build cache from cengn to speed up build. This step can be ignored if rebuild all packages
  - time ./build.sh /stx-ci/scripts/stx-workspace-cache || exit 1
    # Push image to docker hub
  - time ./build.sh /stx-ci/scripts/stx-image-sync || exit 1
  - while true; do echo keep alive ...; sleep 15; done & # workaround for travis limitation
    # Only rebuild sysinv because of build time limitation
    # To rebuild all packages, it needs 'Unlimited build minutes' account. Refer to: https://travis-ci.com/plans
  - time ./build.sh "/stx-ci/scripts/stx-build sysinv" || exit 1 # only re-build sysinv
    # Put the ISO and Helm Charts to docker image for future deploy/test. To use this docker image is still working in progress.
  - mkdir stx-release
  - cp -a localdisk/pub stx-release
  - cd stx-release
  - echo FROM busybox > Dockerfile
  - echo COPY pub /stx-release
  - docker build -t $DOCKER_REPO/stx-release:$DOCKER_IMG_TAG .
  - docker push $DOCKER_REPO/stx-release:$DOCKER_IMG_TAG
