#!/bin/bash -e

: ${MYUNAME:=builder}
: ${MYUID:=1000}
: ${MYPROJECTNAME:=starlingx}
: ${MY_TC_RELEASE:=tis}

if ! id $MYUNAME; then
	echo "setup $MYUNAME ..."
	mkdir -p /home/$MYUNAME
	usermod -l $MYUNAME -d /home/$MYUNAME builder 
	echo "$MYUNAME ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
	sed -i "s/builder/$MYUNAME/g" /etc/lighttpd/lighttpd.conf
fi

chown $MYUID:cgts /home/$MYUNAME/.ssh -R
chown $MYUID:cgts /home/$MYUNAME/.gitconfig

mkdir -p /import/mirrors/CentOS
chown $MYUID:cgts /import -R
chown $MYUID:cgts /localdisk
mkdir -p /localdisk/loadbuild/mock
mkdir -p /localdisk/loadbuild/mock-cache
chown root:mock /localdisk/loadbuild/mock
chmod 775 /localdisk/loadbuild/mock
chown root:mock /localdisk/loadbuild/mock-cache
chmod 775 /localdisk/loadbuild/mock-cache
mkdir -p /localdisk/designer/$MYUNAME/$MYPROJECTNAME
chown $MYUID:cgts /localdisk/designer -R
mkdir -p /localdisk/loadbuild/$MYUNAME/$MYPROJECTNAME
chown $MYUID:cgts /localdisk/loadbuild/$MYUNAME/$MYPROJECTNAME -R

mkdir -p /localdisk/config
echo "$MYUID:$MYUNAME" > /localdisk/config/usr.lst
echo > /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MYUNAME=$MYUNAME" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MYPROJECTNAME=$MYPROJECTNAME" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export USER=$MYUNAME" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export PROJECT=$MYPROJECTNAME" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export SRC_BUILD_ENVIRONMENT=$MY_TC_RELEASE" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_ENVIRONMENT=\$USER-\$PROJECT-\$SRC_BUILD_ENVIRONMENT" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_ENVIRONMENT_FILE=\${MY_BUILD_ENVIRONMENT}.cfg" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_ENVIRONMENT_FILE_STD=\${MY_BUILD_ENVIRONMENT}-std.cfg" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_ENVIRONMENT_FILE_RT=\${MY_BUILD_ENVIRONMENT}-rt.cfg" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_DIR=/localdisk/loadbuild/\$USER/\$PROJECT" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_WORKSPACE=\$MY_BUILD_DIR" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_LOCAL_DISK=/localdisk/designer/\$USER" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_REPO_ROOT_DIR=\$MY_LOCAL_DISK/\$PROJECT" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_REPO=\$MY_REPO_ROOT_DIR/cgcs-root" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_SRC_RPM_BUILD_DIR=\$MY_BUILD_DIR/rpmbuild" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_CFG=\$MY_WORKSPACE/\$MY_BUILD_ENVIRONMENT_FILE" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_CFG_STD=\$MY_WORKSPACE/std/\$MY_BUILD_ENVIRONMENT_FILE_STD" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_BUILD_CFG_RT=\$MY_WORKSPACE/rt/\$MY_BUILD_ENVIRONMENT_FILE_RT" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_DEBUG_BUILD_CFG_STD=\$MY_WORKSPACE/std/configs/\${MY_BUILD_ENVIRONMENT}-std/\${MY_BUILD_ENVIRONMENT}-std.b0.cfg" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_DEBUG_BUILD_CFG_STD=\$MY_WORKSPACE/std/configs/\${MY_BUILD_ENVIRONMENT}-std/\${MY_BUILD_ENVIRONMENT}-rt.b0.cfg" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export MY_MOCK_ROOT=\$MY_WORKSPACE/mock/root" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export FORMAL_BUILD=0" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export PATH=\$MY_REPO/build-tools:\$PATH" >> /localdisk/config/prj-$MYPROJECTNAME.conf
echo "export PATH=/usr/local/bin:/localdisk/designer/\$MYUNAME/bin:\$PATH" >> /localdisk/config/prj-$MYPROJECTNAME.conf
cat >> /localdisk/config/prj-$MYPROJECTNAME.conf <<__EOF__
export PS1='\[\e[38;5;39m\]\u\[\e[0m\]@$MYPROJECTNAME@\[\e[38;5;208m\]\H \[\e[38;5;39m\]\w \[\e[38;5;39m\]$ \[\e[0;0m\]'
__EOF__

chown $MYUID:cgts /localdisk/config -R

sed -i 's/nr_inodes=0/nr_inodes=1000k/g' /usr/lib/python2.7/site-packages/mockbuild/plugins/tmpfs.py 2>/dev/null || true
sed -i 's/nr_inodes=0/nr_inodes=1000k/g' /usr/lib/python3.6/site-packages/mockbuild/plugins/tmpfs.py 2>/dev/null || true
/usr/sbin/lighttpd  -f /etc/lighttpd/lighttpd.conf
