#!/bin/bash -e

sudo -E /stx-ci/scripts/stx-build-setup
source /localdisk/config/prj-$MYPROJECTNAME.conf

: ${STX_RELEASE_URL:=http://mirror.starlingx.cengn.ca/mirror/starlingx/master/centos/latest_build}
: ${MIRROR_PATH:=/import/mirrors/CentOS/mirror}

if [ -e $MIRROR_PATH/.init_done ]; then
    echo mirror init done
    exit 0
fi

mkdir -p $MIRROR_PATH
cd $MIRROR_PATH
wget $STX_RELEASE_URL/outputs/BUILD_INFO.txt
CUTDIR_NUM=$(echo $STX_RELEASE_URL | sed 's/http.*:\/\///g' | sed 's/\/$//g' | awk -F "/" '{print NF}')
wget -q -nH -np -r --cut-dirs=$CUTDIR_NUM -R "*.html"  $STX_RELEASE_URL/inputs/
mv RPMS Binary
mv SRPMS Source

mkdir -p $MIRROR_PATH/../stx-installer
cd $MIRROR_PATH/../stx-installer
CUTDIR_NUM=$(echo $STX_RELEASE_URL/outputs | sed 's/http.*:\/\///g' | sed 's/\/$//g' | awk -F "/" '{print NF}')
wget -q -nH -np -r --cut-dirs=$CUTDIR_NUM -R "*.html"  $STX_RELEASE_URL/outputs/installer

touch $MIRROR_PATH/.init_done
